### ISSUE TITLE
Error: djxl is found but not executable!

### ISSUE THREAD

**Issue by jueank** [kampidh/jxl-batch-converter#1]
Hi,
downloaded the jxl executables from here: https://artifacts.lucaversari.it/libjxl/libjxl/latest/
jxl-batch-converter starts but gives the following error messages:
Error: djxl is found but not executable!
Error: cjpegli is found but not executable!
Error: djpegli is found but not executable!

Interestingly, cjxl.exe is not mentioned in the errors. The tools run fine on commandline (ix x64 & x86)

**Comment by kampidh** [comment]
Hello, are you using win or linux one?
If linux, make sure to set those other tools (djxl, cjpegli, djpegli) permission to execute if you want to use them as well.
If windows, I currently can't reproduce the errors yet..

**Comment by jueank** [comment]
Using it on Windows 11. The files are not located in restricted folders (e.g. C:/Program Files/). What do you check in code in order to identify if they are executable? (Just looked it up myself. Just regular QT lib stuff. Looks identical to the cjxl section which does not report an error). hmmm...

**Comment by jueank** [comment]
Ok. I'm dumb. I was misleaded by the non-occurring error for cjxl.exe. I assumed jxl-batch-converter is looking in the default folder for the cmd line tools, but it doesnot. I have to pick the folder by hand. It's working..
