### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by n-osennij** [kampidh/jxl-batch-converter#3]
If have many images and cpu with many cores it is will by grate have option to load cpu 100% converting images not one by one but multiple
![Снимок экрана 2024-01-11 090458](https://github.com/kampidh/jxl-batch-converter/assets/17576299/d6923fef-e2e4-4414-96f9-a75ee3aa1848)

**Comment by kampidh** [comment]
Added on new release https://github.com/kampidh/jxl-batch-converter/releases/tag/v0.4.0
