### ISSUE TITLE
A few suggestions on how to make the converter even better

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [kampidh/jxl-batch-converter#7]
Add option "**Save to the same folder as the original**". Specifying it manually every time is not very convenient.

Add option "**Delete original**", and the choice - to the Recycle or in the usual way. There should also be a fairly reliable verification of the success of the conversion, preferably based on several parameters:

1. Report from the codec about success.
2. Checking the existence of the new file.
3. Check if the file size is 0 (I have encountered similar cases several times when using other converters and other file formats).
4. Ideally, it would not be superfluous to check the validity using a special tool (I don’t know which one). Or try decoding with the same codec.

Need to add an icon for the program.

Add option "**Clear the list of files after successful conversion**".

Add button "**Remove all files from list**". Currently, such a button remove only the selected files, which is quite strange, since usually need to delete the entire list.

Disadvantage: if the "**multi-threading**" option is selected, then at the end of the process not displayed: total size of incoming files, files after conversion, and the difference in percentage. More precisely, it is displayed only for each thread separately. Of course, need the sum of all the numbers.

Add the option "**If a file with the same name already exists, then add a number to the new file**". It is also advisable to provide for the situation where, for example, the file "**file-1.jxl**" already exists, so that the converter creates the file "**file-2.jxl**" rather than "**file-1-1.jxl**". Or, better, instead of a number, an identifier and some random set of characters, for example “**file-#double-H7u3.jxl**”. The identifier makes it easy to find these files and rename them in the desired way - manually or automatically using one of the specialized programs.

Make sure that the program version is displayed in the "About" tab.

_P.S. Sorry for bad English, I have to use Google translator._

**Comment by kampidh** [comment]
Thanks a lot for the ideas and suggestions! Will consider it for future releases. Some of them will require a bit more works to do, so I can't give any estimation yet.

**Comment by kampidh** [comment]
Implemented in https://github.com/kampidh/jxl-batch-converter/releases/tag/v0.5.0
